---
# tasks file for keymaster

- name: add admin user group to the instance
  group: name=admins state=present

- name: copy the sudoers files
  copy: src=admins-sudo dest=/etc/sudoers.d/admins-sudo

- name: install pynamodb package that we use to read dynamodb
  pip: name=pynamodb state=latest

- name: create the keymaster directory
  file: name=/opt/keymaster state=directory

- name: copy the ansible playbook that updates the users
  copy: src=ssh_create_users.yml dest=/opt/keymaster/ssh_create_users.yml

- name: copy the python script that retrieves data from dynamodb
  copy: src=ssh_dynamodb.py dest=/opt/keymaster/ssh_dynamodb.py mode=0755

- name: copy shell script that executes the cron job
  copy: src=update_ssh_users.sh dest=/opt/keymaster/update_ssh_users.sh mode=0755

- name: create entry to run cron job that adds and remove users
  cron: name="update ssh users" minute="*/{{ 10 |random}}" hour="*" cron_file=keymaster user=root job="/opt/keymaster/update_ssh_users.sh >> /var/log/keymaster.log 2>&1"
