---
# tasks file for new relic
  - name: gather ec2 facts
    action: ec2_facts

  - name: get environment tag
    action: ec2_tag resource={{ ansible_ec2_instance_id }} region={{ ansible_ec2_placement_region }} state=list
    register: allTags

  - file: path=/opt/newrelicnode state=directory

  - name: expand newrelic config template
    template: src=newrelic-config.js.j2 dest=/opt/newrelicnode/newrelic.js owner=root group=root mode=0644
