---

  - name: Download the sidecar package from S3
    s3: bucket=inindca-deploy object=/python/latest/sidecar.tar.gz dest=/tmp/sidecar.tar.gz mode=get

  - name: pip install the downloaded sidecar package
    pip: name='file:///tmp/sidecar.tar.gz'

  - name: register the sidecar service
    sudo: true
    shell: /sbin/chkconfig --add sidecard

  - name: enable the sidecar service with default config
    service: name=sidecard state=started
