---
  - hosts: all
    sudo: true

    tasks:
      - name: gather ec2 facts
        action: ec2_facts

      - name: get environment tag
        action: ec2_tag resource={{ ansible_ec2_instance_id }} region={{ ansible_ec2_placement_region }} state=list
        register: allTags

      - group_by: key={{ allTags.tags.role }}

  - hosts: storm

    roles:
     - storm-configure

  - hosts: nimbus

    roles:
     - nimbus
