---
  - hosts: localhost
    sudo: false

    tasks:
      - name: gather ec2 facts
        action: ec2_facts

      - name: get environment tag
        action: ec2_tag resource={{ ansible_ec2_instance_id }} region={{ ansible_ec2_placement_region }} state=list
        register: allTags

      - debug: var=allTags.tags.role


    roles:
    - { role: storm-configure, when: allTags.tags.role == storm }
    - { role: nimbus, when: allTags.tags.role == nimbus }
    - sumologic
    - newrelicjava
