
- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    keypair: "dev.ops"
    instance_type: "t2.medium"
    image: "ami-08842d60"
    group: "sg-65925600"
    region: "us-east-1"
    zone: "us-east-1b"
    subnet: "subnet-21e7b967"
  tasks:
    - name: make one instance
      ec2: image={{ image }}
           instance_type={{ instance_type }}
           keypair={{ keypair }}
           instance_tags='{"Owner":"Andres Silva"}'
           region={{ region }}
           group_id={{ group }}
           vpc_subnet_id={{ subnet }}
           assign_public_ip=yes
           wait=true
      register: ec2_info

    - debug: var=ec2_info
    - debug: var=item
      with_items: ec2_info.instance_ids

    - add_host: hostname={{ item.public_ip }} groupname=ec2hosts
      with_items: ec2_info.instances

    - name: wait for instances to listen on port:22
      wait_for:
        state=started
        host={{ item.public_dns_name }}
        port=22
      with_items: ec2_info.instances
