---
# tasks file for new sumo
- name: gather ec2 facts
  action: ec2_facts

- name: get environment tag
  action: ec2_tag resource={{ ansible_ec2_instance_id }} region={{ ansible_ec2_placement_region }} state=list
  register: allTags

- name: install the latest version of sumo
  yum: name=SumoCollector state=latest

- name: disable SumoCollector service
  service: name=collector enabled=no
