---
# tasks file for new sumo
- name: gather ec2 facts
  action: ec2_facts

- name: get environment tag
  action: ec2_tag resource={{ ansible_ec2_instance_id }} region={{ ansible_ec2_placement_region }} state=list
  register: allTags

- name: install packages
  yum: pkg={{ item }} state=installed
  with_items:
   - jzmq
   - zeromq
   - unzip
   - storm

- user: name=storm

- template: src=inin.conf.j2 dest=/etc/inin.conf mode=0744

- file: path=/var/storm mode=0744 owner=storm group=storm state=directory recurse=yes

- file: path=/var/log/storm mode=0744 owner=storm group=storm state=directory recurse=yes

- file: path=/var/log/inin mode=0744 owner=storm group=storm state=directory recurse=yes

- copy: src=storm.log.properties dest=/usr/share/storm/log4j/storm.log.properties mode=0644

- copy: src=logrotate dest=/etc/logrotate.d/storm mode=0644

- file: src=/usr/share/storm/conf dest=/etc/storm state=link

- copy: src=configure.sh dest=/opt/configure.sh mode=0755

- shell: echo '/opt/configure.sh' >>/etc/rc.d/rc.local
