---
# tasks file for new sumo
- name: gather ec2 facts
  action: ec2_facts

- name: get environment tag
  action: ec2_tag resource={{ ansible_ec2_instance_id }} region={{ ansible_ec2_placement_region }} state=list
  register: allTags

- template: src=sources.json.j2 dest=/opt/SumoCollector/sources.json owner=root group=root mode=0644
- template: src=sumo.conf.j2 dest=/etc/sumo.conf owner=root group=root mode=0644

- name: Enable SumoCollector service
  service: name=collector enabled=yes state=restarted
