- name: install packages
  yum: name=httpd state=present

- name: install something else
  yum: name=php state=present

- name: enable apache on startup and start service
  service: name=httpd enabled=yes state=started
