---
# tasks file for Spot instance termination notification

- name: gather ec2 facts
  action: ec2_facts

- name: get environment tag
  action: ec2_tag resource={{ ansible_ec2_instance_id }} region={{ ansible_ec2_placement_region }} state=list
  register: allTags

- template: src=spot-termination-notifier.sh.j2 dest=/opt/spot-termination-notifier.sh owner=root group=root mode=0755
- template: src=spot-termination-notifier.ini.j2 dest=/etc/supervisor.d/spot-termination-notifier.ini mode=0744
- supervisorctl: name=spot-termination-notifier state=restarted
