#!/bin/sh
### BEGIN INIT INFO
# Provides:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO


name=`basename $0`

case "$1" in
    start)
      ruby /opt/jc/register.rb
    ;;
    stop)
      ruby /opt/jc/delete.rb
    ;;
esac

exit 0
