---
# tasks file for new relic
  - name: gather ec2 facts
    action: ec2_facts

  - name: get environment tag
    action: ec2_tag resource={{ ansible_ec2_instance_id }} region={{ ansible_ec2_placement_region }} state=list
    register: allTags

  - name: install new relic java agent
    yum: name=newrelic-java state=latest

  - name: create log directory for new relic java agent
    file: path=/var/log/newrelic-java mode=0766 state=directory
