---
# Downloads and saves certificate pair using kms module
#
# usage:
# - { role: certificate-retrieval, cert_directory: "/etc/certs" domain: "inindca.com" }
#
- name: Create cert directory if it doesn't exist
  file: path={{ cert_directory }} state=directory

- name: Fetch Certificates
  kms_decrypt: src=s3://{{ kms_bucket }}/ansible/certs/{{ item }} dest={{ cert_directory }}/{{ item }}
  with_items:
    - "{{ domain }}.crt"
    - "{{ domain }}.key"
  register: certs
