---
# tasks file for new relic

- name: Set newrelic app name for non-opsworks
  set_fact:
    newrelic_role: "{{ service_role }}"
  when: opsworks is undefined or opsworks.stack.name is none

#template nrsysmond.cfg file
- template: src=nrsysmond.cfg.j2 dest=/etc/newrelic/nrsysmond.cfg owner=root group=root mode=0644
- template: src=newrelic.ini.j2 dest=/etc/newrelic/newrelic.ini owner=root group=root mode=0644

- name: Ensure /var/log/newrelic is owned by newrelic
  file: path=/var/log/newrelic state=directory owner=newrelic group=newrelic mode=0755

- name: Enable New Relic Server Agent service
  service: name=newrelic-sysmond enabled=yes state=started
