---
# tasks file for new relic

#template nrsysmond.cfg file
- template: src=nrsysmond.cfg.j2 dest=/etc/newrelic/nrsysmond.cfg owner=root group=root mode=0644

- name: Enable New Relic Server Agent service
  service: name=newrelic-sysmond enabled=yes state=started
