---
# tasks file for jumpcloud

- service: name=jcagent state=restarted enabled=yes

- service: name=jumpcloud enabled=yes

- name: gather ec2 facts
  action: ec2_facts

- name: get environment tag
  action: ec2_tag resource={{ ansible_ec2_instance_id }} region={{ ansible_ec2_placement_region }} state=list
  register: allTags

- template: src=register.rb.j2 dest=/opt/jc/register.rb mode=0755

- copy: src=delete.rb dest=/opt/jc/delete.rb mode=0755

- command: 'ruby /opt/jc/register.rb'
  ignore_errors: yes

- authorized_key: key="{{ key_to_remove }}" user=ec2-user state=absent
  when: remove_key == true
