---
# tasks file for jumpcloud

- command: /opt/kickstart.sh creates=/opt/jc/

- template: src=register.rb.j2 dest=/opt/jc/register.rb mode=0755

- copy: src=delete.rb dest=/opt/jc/delete.rb mode=0755

- service: name=jcagent state=started enabled=yes

- gem: name=jumpcloud version=0.3.0 user_install=yes state=present

- service: name=jumpcloud state=started enabled=yes

- command: '/usr/bin/ruby /opt/jc/register.rb'

#- shell: echo '/opt/remove-ec2-user.sh' >>/etc/rc.d/rc.local
