---
# tasks file for jumpcloud

- copy: src=devops-jumpcloud dest=/etc/init.d/jumpcloud mode=0600

- command: /opt/kickstart.sh creates=/opt/jc/

- template: src=register.rb.j2 dest=/opt/jc/register.rb mode=0755

- copy: src=delete.rb dest=/opt/jc/delete.rb mode=0755

- copy: src=jumpcloud dest=/etc/init.d/jumpcloud mode=0755

- service: name=jumpcloud state=started enabled=yes

- name: remove the ec2 user
  command: find /etc/ -maxdepth 1 -name 'passwd' -o -name 'group' -o -name 'shadow' | xargs sed -i 's/^ec2-user/devops/g'
