---
  - hosts: all
    sudo: true

    roles:
    - system
    - repos
    - newrelic
    - newrelicjava
    - sumologic
    - supervisor
    - jumpcloud-install
    - ossec-install
    - alertlogic-install
