---
  - hosts: all
    sudo: true

    tasks:
      - name: gather ec2 facts
        action: ec2_facts

      - name: get environment tag
        action: ec2_tag resource={{ ansible_ec2_instance_id }} region={{ ansible_ec2_placement_region }} state=list
        register: allTags

      # set the hosname for the instance
      - hostname: name={{ allTags.tags.role }}-{{ ansible_ec2_local_ipv4|replace(".", "-") }}

      - lineinfile: dest=/etc/hosts regexp='^127.0.0.1' line='127.0.0.1 {{ allTags.tags.role }}-{{ ansible_ec2_local_ipv4|replace(".", "-") }}.localdomain {{ allTags.tags.role }}-{{ ansible_ec2_local_ipv4|replace(".", "-") }} localhost localhost.localdomain'

      - group_by: key={{ allTags.tags.environment }}

  - hosts: stage
    sudo: true

    roles:
     - jumpcloud-configure
     - newrelic-configure
     - newrelicjava-configure
     - sumologic-configure
     - newrelicjava
     - ossec-client

  - hosts: prod
    sudo: true

    roles:
     - jumpcloud-configure
     - newrelic-configure
     - newrelicjava-configure
     - sumologic-configure
     - newrelicjava
     - ossec-client

  - hosts: dev
    sudo: true

    roles:
     - newrelic-configure
     - newrelicjava-configure
     - sumologic-configure
     - newrelicjava

  - hosts: test
    sudo: true

    roles:
     - newrelic-configure
     - newrelicjava-configure
     - sumologic-configure
     - newrelicjava
