---
# tasks file for gatekeeper

- name: add admin user group to the instance
  group: name=admins state=present

- name: copy the sudoers files
  copy: src=admins-sudo dest=/etc/sudoers.d/admins-sudo

- name: install pynamodb package that we use to read dynamodb
  pip: name=pynamodb state=latest

- name: create the gatekeeper directory
  file: name=/opt/gatekeeper state=directory

- name: copy the ansible playbook that updates the users
  copy: src=ssh_create_users.yml dest=/opt/gatekeeper/ssh_create_users.yml

- name: copy the python script that retrieves data from dynamodb
  copy: src=ssh_dynamodb.py dest=/opt/gatekeeper/ssh_dynamodb.py mode=0755

- name: copy shell script that executes the cron job
  copy: src=update_ssh_users.sh dest=/opt/gatekeeper/update_ssh_users.sh mode=0755

- name: create entry to run cron job that adds and remove users
  cron: name="update ssh users" minute="*/{{ ['1', '2', '3', '4', '5', '6', '7', '8', '9'] |random}}" hour="*" cron_file=gatekeeper user=root job="/opt/gatekeeper/update_ssh_users.sh >> /var/log/gatekeeper.log 2>&1"
